source("load_data.R")
png("plot3.png",height=480,width=480)
plot(consumption_subset$datetime,consumption_subset$Sub_metering_1,type="l",xlab="",ylab="Energy sub metering")
points(consumption_subset$datetime,consumption_subset$Sub_metering_2,type="l",col="red")
points(consumption_subset$datetime,consumption_subset$Sub_metering_3,type="l",col="blue")
legend("topright",names(consumption_subset)[7:9],col=c("black","red","blue"),lwd=1)
dev.off()